updated github action - build also tests on server;

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -8,6 +8,47 @@ on:
       - '*'
 
 jobs:
+  build-test:
+    name: Build & Test
+    runs-on: ubuntu-latest
+
+    steps:
+      - uses: actions/checkout@v2                                 # checkout the repo
+
+      - name: Install qmltestrunner                               # install required qmltestrunner packages
+        run: |
+          sudo apt-get update -y
+          sudo apt-get install -y qtdeclarative5-dev-tools qml-module-qtquick-localstorage
+          sudo apt-get install -y qml-module-qtquick-controls qml-module-qttest qt5-qmake
+          sudo apt-get install -y libqt5test5 qtbase5-dev qtdeclarative5-dev
+          sudo apt-get install -y libtap-formatter-junit-perl 
+
+      - name: Run QML / C++ Tests
+        run: |
+          set -x
+          cd tests_qml 
+          ./runTests.sh
+          tap2junit --verbose qmlresults.tap
+          sed -i -e 's/><\/t/ classname="-" time="0"><\/t/g' qmlresults.tap.xml
+          sed -i -e 's/testsuite /testsuite time="0" /g' qmlresults.tap.xml
+          sed -i -e 's/<testsuites>/<testsuites name="awtest" tests="0" failures="0" errors="0" time="0.0">/g' qmlresults.tap.xml
+          cd ..                                                   
+          cd tests
+          sudo timedatectl set-timezone Europe/Berlin
+          ./runTests.sh
+          tap2junit --verbose xmlresults.tap
+          sed -i -e 's/><\/t/ classname="-" time="0"><\/t/g' xmlresults.tap.xml 
+          sed -i -e 's/testsuite /testsuite time="0" /g' xmlresults.tap.xml
+          sed -i -e 's/<testsuites>/<testsuites name="awtest" tests="0" failures="0" errors="0" time="0.0">/g' xmlresults.tap.xml
+
+      - name: Test Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure()                                # run this step even if previous step failed
+        with:
+          name: QML/C++ Tests                                     # Name of the check run which will be created
+          path: tests_qml/*.xml,tests/*.xml                       # Path to test results
+          reporter: jest-junit                                    # Format of test results - because junit cannot be generated
+
   build:
     runs-on: ubuntu-latest
 
